### PR TITLE
Chore/update nx

### PR DESCRIPTION
**Pull request by TobbiAR**
Updated nx and angular dependencies via nx migrate

#58

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/effects/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Dependency updates for nx and angular
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- updated nx to angular 16
- updated nx workspace to 16.2.2
- bumped up nodejs version in github actions to 18.10.0 due to dropped support of 
  - angular (https://angular.io/guide/versions) 
  - angular-eslint (https://github.com/angular-eslint/angular-eslint/releases/tag/v16.0.0)

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by EricPoul** [comment]
Could you describe how did you update nx and angular? I still see the migration file in the codebase.

**Comment by TobbiAR** [comment]
Sure,
**Step 1:** I've ran `nx migrate latest`, but faced the problem, that nx didn't manged to update all angular dependencies automatically, so I've used `nx migrate latest --from=nx@15.9.2`.

**Step 2:** To resolve `npm install` errors occurred by a unresolvable peer dependency caused by `@angular-devkit/build-angular`, I've manually updated `jest` and `jest-environment-jsdom` to `v29.5.0` to be able to run npm i without errors.

**Step 3:** To run (eventually) necessary migrations I've also ran `nx migrate --run-migrations --create-commits`, but nx said, that no migrations are necessary.

**Comment by EricPoul** [comment]
I face an error about `unresolvable peer dependency` every time. I just use ` --legacy-peer-deps`. I tried it and 3rd step passed properly.

**Comment by TobbiAR** [comment]
@EricPoul Ok, I've discovered the root cause of the problem: The pipeline used an outdated nodejs version (v14), which is now unsupported by angular and eslint. The PR should be now ready for review. 🙂

**Pull request merged**
